version: "3.8"

services:
  kirbycms:
    build:
      context: ./demo/kirbycms
      target: dev-stage
    container_name: 11ty-plugin-kirby-cms
    ports:
      - 3002:80
    volumes:
      - ./demo/kirbycms:/app:rw
  11ty:
    tty: true
    build:
      context: .
    container_name: 11ty-plugin-kirby-frontend
    environment:
      - NPM_PACKAGE_NAME=eleventy-plugin-kirby
      - NPM_TOKEN="${NPM_TOKEN}"
    command: npm run watch
    ports:
      - 3000:3000
      - 3001:3001
    volumes:
      - ./:/app:rw
      - ~/.gitconfig:/etc/gitconfig
    depends_on:
      - kirbycms
